### PR TITLE
Unobtrusive browser launch + improved support for OS X, Windows and Linux

### PR DESCRIPTION
**Pull request by luisjakon**

### CODE REVIEW

**Comment by wirepair** [comment]
Thank you kindly!

**Comment by luisjakon** [comment]
My pleasure.  Great work btw!!!  Thnxs

**Comment by wirepair** [comment]
Thanks, and stay tuned, I just wrote an automation library around this that mimics webdriver. Gives a lot more functionality and a lot more usable than this one! Should release in a month or so after I battle test it.

**Comment by luisjakon** [comment]
Awesome!  I will...

**Pull request merged**
