### PR TITLE
Added functionality to connect to remote instances

### PR DESCRIPTION
**Pull request by fgeertsema**
Thank you for this library.
I have added functionality to connect to a remote chrome instance instead of using the local one.

### CODE REVIEW

**Comment by wirepair** [comment]
Thanks for the PR!

**Comment by wirepair** [comment]
Seems like this test fails in windows did you test it out on other OS's?

**Comment by fgeertsema** [comment]
No I only tested it on a Mac.
What kind of error did you get?

**Comment by wirepair** [comment]
I timed out trying to connect to debugger.

**Pull request merged**
